In [1]:
#using lambda functions ; lambda are anonymous functions and return one expression only
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    result=lambda person:person.split()[0] + ' ' + person.split()[-1]
    print(split_title_and_name(person) == result(person))

#option 2
result=lambda person:person.split()[0] + ' ' + person.split()[-1]
print(type(result))
list(map(split_title_and_name, people)) == list(map(result,people))

True
True
True
True
<class 'function'>


True

In [2]:
# practice exercises from Coursera - applied data science
# using map function ; take four names in a list and generate an output thats combination of Title and last name 
# given list of names
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']
def split_names(person):
    return person.split(' ')[0]+" "+person.split(' ')[-1]
list(map(split_names,people))


['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [7]:
#list comprehensions 
list1=range(0,10)
number=[]
#print only even numbers between0 to 10 using list comprehensions
mylist=[number for number in list1 if number%2==0]
print (mylist)

#function that returns product of numbers.
def times_tables():
    lst = []
    for i in range(3):
        for j in range (3):
            lst.append(i*j)
    return lst
print(times_tables())

# same product of numbers function written as list comprehension
list2=[num1*num2 for num1 in range(3) for num2 in range(3) ]
print(list2)

#square of numbers using list comprehension 
list3=[num1**2 for num1 in range(4)]
print(list3)

[0, 2, 4, 6, 8]
[0, 0, 0, 0, 1, 2, 0, 2, 4]
[0, 0, 0, 0, 1, 2, 0, 2, 4]
[0, 1, 4, 9]


In [41]:
#list comprehension to create possible user ids from alphabets and digits such that user id is first 2 chars and next 2 digits
lowercase='abcdefghijklmnopqrstuvwxyz'
digits='0123456789'
#digits[::2]
#type(digits)
#type(lowercase)
# for u1 in lowercase:
#     for u2 in lowercase:
#         print(u1+u2)
userid=[u1+u2+u3+u4 for u1 in lowercase for u2 in lowercase for u3 in digits for u4 in digits]
print(userid[-1])

zz99


In [67]:
# str1='abcde'
# print(str1)
# str1=str1+'abcdef'
# print(str1)
# tup1=(1,2,3)
# print(tup1)
# tup1=tup1+(1,2,3,4,5)
# print(tup1)
#print(['a','b','c']+[1,2,3])
import numpy as np
arr1=np.arange(0,36)
#print(arr1)
#print(arr1.shape)
arr1.resize(6,6)
print(arr1)
#print(arr1.reshape(36))[::7]
#print(arr1[0:6,::-7])
#print(arr1[::7])
print(arr1.reshape(36)[::7])
#print(arr1[::8])
print(arr1[2:4,2:4])


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[ 0  7 14 21 28 35]
[[14 15]
 [20 21]]


In [343]:
#Dataframe
import pandas as pd
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})

df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
#df.where((df.Cost>3.00))
#print(df['Item Purchased'])
# df.Cost=df.Cost*0.8
#df.loc["Store 1"]
#df.iloc[1:]
Location=df.index.values
# print(type(Location))
# print(Location)
# print(len(Location))
# print(Location.shape)
#print(Location.T)

#df.columns.append(Location)
#df.columns+=Location
#df.columns
df1=df.copy()
df1=df1.assign(Locn=Location)
#df1.set_index(['Location',df1.Name])
#print(df1)
df1=df1.reset_index(drop=True)
df1=df1.set_index(['Locn','Name'])
#df1=df1.set_index([Locn][Name])
#set_index
#print(df1)
#print(df1.Locn)
#df1.index
# Location=[df1.index]
# print(len(Location))
# print(len(df1.index))
# print(df1.index)
# print(Location)
#df1.assign(Locn=Location)
#df1=df1.align('Locn':'Store2','Name':'Kevyn','Cost':'3.00','Item Purchased':'Kitty Food')
df1
#df1.loc['Locn','Name'][0]

#df1.loc['Locn']['Name'][0]
#df1.index.append
# S1=pd.Series({'Locn':'Store2','Name':'Kevyn','Cost':'3.00','Item Purchased':'Kitty Food'})
# S1
# df1.append(S1,ignore_index=True)
# #df1.append(['Store2'])
#df1=df1.align('Locn':'Store2','Name':'Kevyn','Cost':'3.00','Item Purchased':'Kitty Food')
#df1=df1.append('Locn':'Store2','Name':'Kevyn','Cost':'3.00','Item Purchased':'Kitty Food')
# df1
#df1.align('Store2','Kevyn','3.00','Kitty Food')
# df2=pd.DataFrame(data=['Store2','Kevyn','3.00','Kitty Food'],index=['Store2','Kevyn'])
# df2

Cost Item Purchased
Locn    Name                      
Store 1 Chris  22.5       Dog Food
        Kevyn   2.5   Kitty Litter
Store 2 Vinod   5.0      Bird Seed

In [341]:
# products ={
#     'Product ID':[4109,1412,8931],
#     'Price':[5.0,0.5,1.5],
#     'Product':['Sushi Roll','Egg','Bagel']
# }
# invoices ={
#     'Customer':['Ali','Eric','Ande','Sam'],
#     'Product ID':[4109,1412,8931,4109],
#     'Quantity':[1,12,6,2]
# }
# Pro_df=pd.DataFrame(data=products)
# Inv_df=pd.DataFrame(data=invoices)
# # print(Pro_df)
# # print(Inv_df)
# Pro_df=Pro_df.set_index('Product ID')
# Inv_df=Inv_df.set_index('Product ID')
# # print(Pro_df)
# # print(Inv_df)
# Total_df=pd.merge(
#     Pro_df,Inv_df,how='outer',left_index=True,right_index=True
# )
# #print(Total_df)
# Total_df['Total']=Total_df['Price']*Total_df['Quantity']
# print(Total_df)
# Total_df['Price'].rename='Price(USD)'
# print(Total_df)


SyntaxError: invalid syntax (<ipython-input-341-28be395a0eed>, line 27)

In [5]:
# df=df.rename_axis("Location",axis="columns")
# S1=df.iloc[0]
# print(S1.name)
# df.iloc[0].name
#df2=df.groupby('Name')
#df2.count?
#df1.iloc[:,1]
#df.sort_values(by='Cost',ascending=False).head(1)
# df.columns
# df1.columns
import numpy as np
import pandas as pd
data1=np.arange(1,10)
data1
data2=np.arange(0,9)
data2
# index
df1=pd.DataFrame(data1,index=data2)
col2=df1[0]*3
df1=df1.assign(col2=col2)
col3=df1[0]*df1['col2']
col4=df1['col2']+6
df1=df1.assign(col3=col3)
df1=df1.assign(col4=col4)
#df1.ind

df1.set_index=['col2','col3']
#df1               
#df1.pivot_table(aggfunc=,)

In [445]:
#load excel file 
energy1=pd.read_excel("Energy Indicators.xlsx")
#energy1
#creating data frame
energy=pd.DataFrame(data=energy1)
#dropping junk rows and first 2 columns
energy=energy.iloc[16:,2:6]
energy.tail(20)

#renaming columns
energy=energy.rename(columns=
               {
                   'Environmental Indicators: Energy':'Country',
                   'Unnamed: 3':'Energy Supply',
                   'Unnamed: 4':'Energy Supply per Capita',
                   'Unnamed: 5':'% Renewable'
               }
            )
#energy
#converting petajoules to Gigajoules
PetatoGiga=lambda x:x*1000000
energy['Energy Supply']=PetatoGiga(energy['Energy Supply'])
energy
energy_cp=energy
energy_cp['Energy Supply']=pd.to_numeric(energy_cp['Energy Supply'],errors='Coerce')
energy_cp['Energy Supply per Capita']=pd.to_numeric(energy_cp['Energy Supply per Capita'],errors='Coerce')
energy_cp.describe()
energy_cp=energy_cp.loc[:249]
energy_cp
S1=energy_cp['Country']
S1=S1.replace({'Republic of Korea':'South Korea',
                                       'United States of America20': 'United States',
                                         'United Kingdom of Great Britain and Northern Ireland19': 'United Kingdom',
                                         'China, Hong Kong Special Administrative Region3': 'Hong Kong'
                                        }
                                       )
S1
energy_cp=energy_cp.rename(columns={'Country':'Country1'})
energy_cp
energy_cp['Country']=S1
energy_cp=energy_cp.drop(columns='Country1')
energy_cp
S1=energy_cp['Country']

pdf=S1.str.extract("(?P<paren>[\(])",expand=True)
pdf_1=pdf.dropna()


pdf1=S1.str.extract("(?P<digit>\d)",expand=True)
pdf1_1=pdf1.dropna()

#40,66,72,86,114,129,149,199,237
lst1=[]
lst2=[]
for i in pdf1_1.index.values:
    lst1.append(S1.loc[i])
for i in range(0,len(lst1)):
    lst1[i]=lst1[i][0:len(lst1[i])-1]

S2=pd.Series(lst1[0:])
pdf2=S2.str.extract("(?P<digit>\d)",expand=True)
pdf2
pdf2=pdf2.dropna()
for i in pdf2.index.values:
    lst2.append(lst1[i])
lst2
for i in range(0,len(lst2)):
    lst2[i]=lst2[i][0:len(lst2[i])-1]
lst2

#lst_0=[]
lst_1=[]
for i in pdf_1.index.values:
    #print(S1.loc[i])
    lst=S1.loc[i]
    lst_1.append(lst[0:(lst.find("("))-1])
#without parentheses
Lst_no_paren=lst_1
#without digits
pdf2.index.values[0]
lst1[0:(pdf2.index.values[0])-1]
lst2
Lst_no_digits=lst1[0:(pdf2.index.values[0])-1]+lst2
#printing both 
Lst_no_paren
Lst_no_digits
#final list 
Lst_final =Lst_no_paren+Lst_no_digits
Lst_final
#S1.replace(S1.str.match("Bolivia")
#S1.loc[40]
#S1
#pdf.isna().index.values
#pdf3=S1.str.extract("(?P<paren>[\(])|(?P<digit>\d)",expand=True)
#pdf_1.index.values
#pdf1_1.index.values
# for i in range(0,len(lst)):
#     lst_1.append(lst[i][0:(lst.find("("))-1])          
# lst_0  
#lst_1
# lst=[S1.loc[40]]
# lst
# lst_1=lst[0:(lst.str.find("("))-1]
# lst_1
#len(lst)
#lst[8]
#['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
#second rename :
# "Republic of Korea": "South Korea",
# "United States of America": "United States",
# "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
# "China, Hong Kong Special Administrative Region": "Hong Kong"

'Bolivia (Plurinational State of)'